### ISSUE TITLE
Update website: Link to pypdf_table_extraction

### ISSUE THREAD

**Issue by bosd** [py-pdf/py-pdf.github.io#6]
Since [pypdf_table_extraction](https://github.com/py-pdf/pypdf_table_extraction) is now part of pypdf organization.
Please add a link to it on the website.

**Comment by Lucas-C** [comment]
Hi @bosd

Would you like to contribute a PR to add a new link in this list?
https://github.com/py-pdf/py-pdf.github.io/blob/main/pelicanconf.py#L21

**Comment by Lucas-C** [comment]
I published a new version of the website by rebasing the `gh-pages` branch onto the `main` branch:

    git checkout main && git pull
    git checkout gh-pages && git pull
    git rebase main
    make github

Note sure if that was the expected way to do it (maybe a PR or a `git merge` would have been better), but it worked!
